# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
neo_version=47.4.10
loom.platform = forge

# Mod Properties
mod_version=2.6.1
maven_group=ivorius.pandorasbox
archives_base_name=pandorasbox
sub_version=release

#Fabric api
fabric_version=0.92.6+1.11.14+1.20.1
atlas_core_version=1.1.2.beta.6-1.20.1-Forge
packet_tweaker=0.4.0+1.19.4

# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20,1.20.2)
# The Forge version range can use any version of Forge as bounds or match the loader version range
forge_version_range=[47,48)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,48)


## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=pandorasbox
# The human-readable display name for the mod.
mod_name=Pandora's Box
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Ivorius, Alexandra
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Adds Pandora's Box to the game. What does it do? There's only one way to find out...