/*
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 */

// Date: 18.04.2014 00:26:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package ivorius.pandorasbox.client.rendering;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import ivorius.pandorasbox.entitites.PandorasBoxEntity;
import net.minecraft.client.renderer.entity.model.SegmentedModel;
import net.minecraft.client.renderer.model.ModelRenderer;

import java.util.Arrays;

public class PandorasBoxModel extends SegmentedModel<PandorasBoxEntity> {
    private final ModelRenderer feet;
    private final ModelRenderer body;
    private final ModelRenderer joint;
    private final ModelRenderer top;
    private final ModelRenderer[] parts;

    public PandorasBoxModel() {
        texWidth = 32;
        texHeight = 32;

        feet = new ModelRenderer(this);
        feet.setPos(0.0F, 1.0F, 0.0F);
        feet.addBox(0, 14, -3.0F, 22.0F, 2.0F, 1, 1, 1, 0.0F);
        feet.addBox(4, 14, 2.0F, 22.0F, 2.0F, 1, 1, 1, 0.0F);
        feet.addBox(4, 16, 2.0F, 22.0F, -3.0F, 1, 1, 1, 0.0F);
        feet.addBox(0, 16, -3.0F, 22.0F, -3.0F, 1, 1, 1, 0.0F);
        setRotationAngle(feet, 0, 0, 0);

        body = new ModelRenderer(this);
        body.setPos(0.0F, 24.0F, 0.0F);
        body.addBox( 0, 0, -4.0F, -7.0F, -4.0F, 8, 6, 8, 0.0F);
        setRotationAngle(body, 0, 0, 0);

        joint = new ModelRenderer(this);
        joint.setPos(0.0F, 24.0F, 0.0F);
        joint.addBox(8, 14, -3.5F, -8.0F, -4.0F, 7, 1, 1, 0.0F);
        setRotationAngle(joint, 0, 0, 0);

        top = new ModelRenderer(this);
        top.setPos(0.0F, 24.0F, 0.0F);
        setRotationAngle(top, -0.0366F, 0.0F, 0.0F);
        top.addBox(0, 18, -4.0F, -8.0F, -4.0F, 8, 1, 8, 0.0F);
        top.addBox(0, 27, -2.0F, -9.0F, -2.0F, 4, 1, 4, 0.0F);
        top.addBox(8, 16, -3.0F, -8.5F, -0.5F, 1, 1, 1, 0.0F);
        top.addBox(8, 16, 2.0F, -8.5F, -0.5F, 1, 1, 1, 0.0F);
        top.addBox(8, 16, -0.5F, -8.5F, -3.0F, 1, 1, 1, 0.0F);
        top.addBox(8, 16, -0.5F, -8.5F, 2.0F, 1, 1, 1, 0.0F);
        parts = new ModelRenderer[]{feet, body, joint, top};
        for(ModelRenderer part : parts) {
            part.setTexSize(32, 32);
        }
    }

    @Override
    public void setupAnim(PandorasBoxEntity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        top.xRot = entityIn.xRot;
    }

    public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.xRot = x;
        modelRenderer.yRot = y;
        modelRenderer.zRot = z;
    }

    @Override
    public Iterable<ModelRenderer> parts() {
        return Arrays.asList(parts);
    }
}